### RELEASE IMAGE ###
FROM docker.io/alpine:3.21

RUN apk --no-cache add ca-certificates tzdata
RUN addgroup -S application --gid 10001 && adduser -S application -G application --uid 10001
RUN mkdir -p /logs && chown -R application:application /logs

WORKDIR /app

COPY picosend /app/
RUN chown -R application:application /app

USER application
ENV LOG_DIR=/logs
EXPOSE 8080
ENTRYPOINT ["/app/picosend"]
