### RELEASE IMAGE ###
FROM docker.io/alpine:3.22

LABEL description="PicoSend: Share secrets securely. Once read, they're gone forever"


RUN apk --no-cache add ca-certificates tzdata
RUN addgroup -S application --gid 10001 && adduser -S application -G application --uid 10001
RUN mkdir -p /logs && chown -R application:application /logs

WORKDIR /app

COPY picosend /app/
RUN chown -R application:application /app

USER application
EXPOSE 8080
ENTRYPOINT ["/app/picosend"]
